# Generated by Django 5.2 on 2025-04-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('monthly_list', models.IntegerField(default=0)),
                ('world_rank', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
            ],
        ),
    ]
