# Generated by Django 5.2 on 2025-05-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_spotify_favoritado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotify',
            name='favoritado',
            field=models.BooleanField(default=True),
        ),
    ]
