# Generated by Django 5.2 on 2025-05-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_alter_spotify_favoritado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotify',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
