# Generated by Django 5.2 on 2025-05-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_alter_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotify',
            name='id_artista',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='spotify',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
