# Generated by Django 5.2 on 2025-05-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_spotify_id_artista_alter_spotify_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotify',
            name='id',
        ),
        migrations.AlterField(
            model_name='spotify',
            name='id_artista',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
