# Generated by Django 5.2 on 2025-05-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_remove_spotify_id_alter_spotify_id_artista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotify',
            name='id_artista',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
