# Generated by Django 5.2 on 2025-05-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_alter_spotify_id_artista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotify',
            old_name='id_artista',
            new_name='id',
        ),
    ]
