# Generated by Django 5.2 on 2025-05-05 15:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_rename_id_artista_spotify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotify',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
