# Generated by Django 5.2 on 2025-05-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0009_alter_spotify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotify',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
