# Generated by Django 5.2 on 2025-05-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0011_remove_spotify_id_spotify_id_artista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=200)),
                ('minima', models.FloatField()),
                ('maxima', models.FloatField()),
                ('chance_chuva', models.FloatField()),
                ('data', models.DateField()),
            ],
        ),
    ]
