# Generated by Django 5.1.6 on 2025-03-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_note_tags_note_tag_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
