# Generated by Django 5.1.6 on 2025-04-01 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='notes.categoria'),
        ),
    ]
