# Generated by Django 5.2 on 2025-05-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spotify',
            fields=[
                ('id_artista', models.CharField(default='', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(default='')),
                ('monthly_list', models.IntegerField(default=0)),
                ('world_rank', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('favoritado', models.BooleanField(default=True)),
            ],
        ),
    ]
