# Generated by Django 5.2.1 on 2025-05-15 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula1',
            fields=[
                ('login', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(default='')),
                ('favpilot1', models.UUIDField(default='')),
                ('favpilot2', models.UUIDField(default='')),
                ('favteam', models.UUIDField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Spotify',
        ),
    ]
