# Generated by Django 5.2.1 on 2025-05-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0002_formula1_delete_spotify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formula1',
            old_name='favpilot1',
            new_name='favpilot',
        ),
        migrations.RemoveField(
            model_name='formula1',
            name='favpilot2',
        ),
        migrations.RemoveField(
            model_name='formula1',
            name='name',
        ),
    ]
