# Generated by Django 5.2.1 on 2025-05-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0003_rename_favpilot1_formula1_favpilot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula1',
            name='p_favoritado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formula1',
            name='t_favoritado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='formula1',
            name='favpilot',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='formula1',
            name='favteam',
            field=models.CharField(default='', max_length=255),
        ),
    ]
